---
deployment:
 tasks:
 - export DEPLOYPATH=/home/merriman/public_html/
 - export REPOPATH=/home/merriman/repositories/merriman.industries
 - /bin/rm -R $DEPLOYPATH
 - /bin/cp -a $REPOPATH/public/. $DEPLOYPATH
